
name: Update Repo with result

on:
#  schedule:
#    - cron: '0 */3 * * *' # Run every 3 hours
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-r-
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("RSQLite","readr","dplyr","rmarkdown","knitr","readxl","openxlsx","ggplot2","scales","tidyr","lubridate","naniar"))'
      - name: Execute R Script
        run: |
          Rscript data_analysis.R
          Rscript load.R

      - name: Add files
        run: |
          git config --global user.email "guptanitya200@gmail.com"
          git config --global user.name "nitya0612"
          git add my_database.db
          git add new_database.db
          git add analysis_graphs/*.png
          
      - name: Commit files
        run: |
          git commit -m "Run the latest Rscritp"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
